MODULES += os/net/security/cose
MODULES += os/net/app-layer/coap
MODULES += os/net/security/micro-ecc
MODULES += os/services/ecc

# Enable Contiki-NG's platform-independent ECC API
CFLAGS += -DECC_CONF_ENABLED=1

ifneq ($(MAKE_EDHOC_METHOD),)
  CFLAGS += -DEDHOC_METHOD=$(MAKE_EDHOC_METHOD)
endif
