CONTIKI_PROJECT = udp-echo
all: $(CONTIKI_PROJECT)

# Enable Rust support
RUST_SUPPORT = 1

# Platforms that don't support Rust yet
PLATFORMS_EXCLUDE += sky z1

CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
